version: "3.2"

services:
  database:
    restart: always
    image: mysql:latest
    ports:
      - 3309:3309
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data
    restart: always
volumes:
  mysql-datavolume:
    driver: local
