services:
  # Staging
  - type: web
    name: test-app-api
    env: ruby
    region: singapore
    plan: free
    branch: master
    numInstances: 1
    healthCheckPath: /
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: LANG
        value: en_US.UTF-8
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: test-app-db
          property: connectionString
      - fromGroup: app-demo-secrets
    autoDeploy: false

  - type: pserv
    name: test-app-db
    env: docker
    region: singapore
    plan: starter
    branch: master
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
    - key: MYSQL_DATABASE
      sync: false
    - key: MYSQL_USER
      sync: false
    - key: MYSQL_PASSWORD
      generateValue: true
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true
    - fromGroup: app-demo-secrets
    autoDeploy: false

envVarGroups:
  - name:  app-demo-secrets
    envVars:
    - key: SECRET_KEY_BASE
      sync: false
    - key: MYSQL_DATABASE
      sync: false
    - key: MYSQL_USER
      sync: false
    - key: MYSQL_PASSWORD
      generateValue: true
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true
