services:
  # Staging
  - type: web
    name: test-app-api
    env: ruby
    region: singapore
    plan: free
    branch: master
    numInstances: 1
    healthCheckPath: /
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: LANG
        value: en_US.UTF-8
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: test-app-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
    autoDeploy: false

databases:
  - name: test-app-db
    region: singapore
    ipAllowList:
      - source: 0.0.0.0
        description: everywhere # staging 環境は直接接続できるように
